# Generated by Django 4.0.6 on 2022-07-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.place'),
        ),
    ]
